import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

for (const width of [320, 390, 640, 768, 1024, 1440]) {
  test('responsive page and assets at ' + width + 'px', async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
    await page.goto('/')
    await expect(page).toHaveTitle('NOMAD Build — Санаанаас бодит орон зай.')
    await expect(page.locator('html')).toHaveAttribute('lang', 'mn')
    await expect(page.locator('.service-row')).toHaveCount(4)
    await expect(page.locator('.project-card')).toHaveCount(4)
    await expect(page.locator('.process-step')).toHaveCount(4)
    await expect(page.locator('.review')).toHaveCount(3)
    for (const id of ['home', 'services', 'projects', 'about', 'process', 'contact']) {
      await page.locator('#' + id).scrollIntoViewIfNeeded()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    }
    await page.locator('footer').scrollIntoViewIfNeeded()
    await page.evaluate(() => document.fonts.ready)
    await expect.poll(() => page.locator('img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0))).toBe(true)
    expect(await page.locator('a[href^="#"]').evaluateAll(links => links.every(link => document.querySelector(link.getAttribute('href')!) !== null))).toBe(true)
    expect(await page.locator('a[target="_blank"]').evaluateAll(links => links.every(link => link.getAttribute('rel')?.includes('noopener') && link.getAttribute('href')?.startsWith('https://')))).toBe(true)
    expect(await page.locator('h1,h2,h3,p,button,input,select,textarea').evaluateAll(nodes => nodes.filter(node => node.clientWidth > 0 && node.scrollWidth > node.clientWidth + 2).map(node => node.textContent))).toEqual([])
    await expect(page.locator('.contact-phone')).toHaveAttribute('href', 'tel:+97677002020')
    await expect(page.locator('.contact-item a[href^="mailto:"]')).toHaveAttribute('href', 'mailto:hello@nomadbuild.example')
    await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }))
    await page.screenshot({ path: 'test-results/nomad-' + width + '-full.png', fullPage: true })
    await page.screenshot({ path: 'test-results/nomad-' + width + '-hero.png' })
    expect(errors).toEqual([])
  })
}

test('project filters show the matching work and preserve correct details', async ({ page }) => {
  await page.goto('/')
  const filters = page.getByRole('group', { name: 'Төслийн ангилал' })
  await filters.getByRole('button', { name: 'Барилга', exact: true }).click()
  await expect(page.locator('.project-card')).toHaveCount(1)
  await expect(page.locator('.project-count')).toHaveText('01 төсөл')
  await page.locator('.project-card').click()
  await expect(page.locator('#project-dialog-title')).toHaveText('Түшиг хаус')
  await page.keyboard.press('Escape')
  await filters.getByRole('button', { name: 'Интерьер', exact: true }).click()
  await expect(page.locator('.project-card')).toHaveCount(3)
  await filters.getByRole('button', { name: 'Бүгд', exact: true }).click()
  await expect(page.locator('.project-card')).toHaveCount(4)
})

test('project dialogs work on a short screen, trap and restore focus', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  for (let i = 0; i < 4; i++) {
    const card = page.locator('.project-card').nth(i)
    const source = await card.locator('img').getAttribute('src')
    await card.click()
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    await expect(dialog.locator('.dialog-photo')).toHaveAttribute('src', source!)
    const box = await dialog.boundingBox()
    expect(box!.width).toBeLessThanOrEqual(320)
    expect(box!.height).toBeLessThanOrEqual(568)
    expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await page.keyboard.press('Shift+Tab')
    await expect(dialog.locator('.button')).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(dialog.locator('.dialog-close')).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(card).toBeFocused()
    expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
  }
})

test('form explains invalid input, focuses errors and confirms a local demo only', async ({ page }) => {
  await page.goto('/')
  const posts: string[] = []
  page.on('request', request => { if (request.method() === 'POST') posts.push(request.url()) })
  const form = page.locator('form')
  await form.getByRole('button', { name: 'Илгээх', exact: true }).click()
  await expect(page.locator('#quote-name')).toBeFocused()
  await expect(page.locator('.field-error')).toHaveCount(4)
  await page.locator('#quote-name').fill('Тест хэрэглэгч')
  await page.locator('#quote-phone').fill('123')
  await page.locator('#quote-email').fill('invalid@')
  await page.locator('#quote-type').selectOption('renovation')
  await page.locator('#quote-message').fill('80 м² орон сууцны иж бүрэн засвар хийлгэх хүсэлтэй.')
  await form.getByRole('button', { name: 'Илгээх', exact: true }).click()
  await expect(page.locator('#quote-phone')).toBeFocused()
  await expect(page.locator('.field-error')).toHaveCount(2)
  await page.locator('#quote-phone').fill('+976 9911 2233')
  await page.locator('#quote-email').fill('test@example.com')
  await form.getByRole('button', { name: 'Илгээх', exact: true }).click()
  await expect(page.locator('.success-message')).toContainText('хүсэлтийг илгээгээгүй')
  await expect(page.locator('.field-error')).toHaveCount(0)
  expect(posts).toEqual([])
  await form.getByRole('button', { name: 'Шинээр бөглөх' }).click()
  await expect(page.locator('#quote-name')).toHaveValue('')
  await expect(page.locator('#quote-type')).toHaveValue('')
  await expect(page.locator('#quote-name')).toBeFocused()
  await expect(page.locator('.success-message')).toHaveCount(0)
})

test('service and project quote links select the service without losing entered text', async ({ page }) => {
  await page.goto('/')
  await page.locator('#quote-name').fill('Тест')
  for (const [i, service] of ['construction', 'interior', 'renovation', 'management'].entries()) {
    await page.locator('.service-link').nth(i).click()
    await expect(page).toHaveURL(/#contact/)
    await expect(page.locator('#quote-type')).toHaveValue(service)
    await expect(page.locator('#quote-name')).toHaveValue('Тест')
  }
  await page.locator('.project-card').nth(2).click()
  await page.getByRole('dialog').locator('.button').click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('#quote-type')).toHaveValue('construction')
  await page.locator('#quote-type').selectOption('renovation')
  await page.locator('.service-link').first().click()
  await expect(page.locator('#quote-type')).toHaveValue('construction')
})

test('mobile menu supports links, Escape, its quote CTA and desktop resizing', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const toggle = page.locator('.menu-toggle')
  const nav = page.getByRole('navigation', { name: 'Гар утасны цэс' })
  await toggle.click()
  await expect(nav).toBeVisible()
  await nav.getByRole('link', { name: 'Төслүүд', exact: false }).click()
  await expect(page).toHaveURL(/#projects/)
  await expect(nav).toBeHidden()
  await toggle.click()
  await page.keyboard.press('Escape')
  await expect(nav).toBeHidden()
  await expect(toggle).toBeFocused()
  await toggle.click()
  await nav.locator('.mobile-quote').click()
  await expect(page).toHaveURL(/#contact/)
  await expect(nav).toBeHidden()
  await toggle.click()
  await page.setViewportSize({ width: 1440, height: 900 })
  await expect(nav).toBeHidden()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
})

test('glass navbar and entrance animations respect scroll and reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  const header = page.locator('.site-header')
  await expect(header).not.toHaveClass(/is-scrolled/)
  await page.evaluate(() => scrollTo({ top: 1000, behavior: 'instant' }))
  await expect(header).toHaveClass(/is-scrolled/)
  await expect(header).toHaveCSS('backdrop-filter', 'blur(18px)')
  await page.locator('#services').scrollIntoViewIfNeeded()
  await expect(page.locator('.services .section-heading')).toHaveCSS('opacity', '1')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.cta .reveal')).toHaveCSS('opacity', '1')
  await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }))
  await expect(header).not.toHaveClass(/is-scrolled/)
})

for (const width of [390, 1440]) {
  test('accessible page, form errors and project dialog at ' + width + 'px', async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await page.locator('footer').scrollIntoViewIfNeeded()
    expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
    await page.locator('form button[type="submit"]').click()
    expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
    await page.locator('.project-card').first().click()
    expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  })
}
