import { useState } from 'react'
import { benefits, contact, navigation, process, projects, reviews, services } from './data'
import type { Project, ServiceId } from './data'
import { ContactForm, Icon, Label, Logo, Navbar, ProjectDialog, QuoteLink, Reveal } from './components'

function Hero() {
  return <section id="home" className="hero" aria-labelledby="hero-title">
    <img className="hero-photo" src="/images/architecture.jpg" alt="Шил, металл фасадтай, геометрийн тод хэлбэр бүхий орчин үеийн барилга" width="1800" height="1200" fetchPriority="high" />
    <div className="hero-shade" /><div className="hero-gridlines" aria-hidden="true" />
    <div className="wrap hero-content"><Label>БАРИЛГА · ИНТЕРЬЕР · ГҮЙЦЭТГЭЛ</Label><h1 id="hero-title">Санаанаас<br />бодит <span>орон зай.</span></h1><p>Таны хэрэгцээнд нийцсэн төлөвлөлт.<br />Деталь бүрд анхаарсан гүйцэтгэл.</p><div className="hero-actions"><QuoteLink /><a className="button button-outline" href="#projects">Төслүүд үзэх<Icon name="arrow" /></a></div></div>
    <div className="wrap hero-bottom"><p>УЛААНБААТАР, МОНГОЛ<span>Төлөвлөлтөөс гүйцэтгэл хүртэл.</span></p><a href="#services" className="scroll-cue" aria-label="Үйлчилгээтэй танилцах"><span>ДООШ ГҮЙЛГЭХ</span><span className="scroll-arrow">↓</span></a><span className="hero-edition" aria-hidden="true">N / 01</span></div>
  </section>
}
function Stats() {
  return <section className="stats" aria-label="Компанийн жишээ үзүүлэлтүүд"><div className="wrap"><div className="stats-grid grid grid-cols-2 lg:grid-cols-4">{[{ value: '8', suffix: '+', label: 'жилийн туршлага' }, { value: '120', suffix: '+', label: 'хэрэгжүүлсэн төсөл' }, { value: '60', suffix: '+', label: 'харилцагч' }, { value: '15', suffix: '', label: 'мэргэжилтэн' }].map(stat => <div className="stat" key={stat.label}><strong>{stat.value}<span>{stat.suffix}</span></strong><p>{stat.label}</p></div>)}</div><p className="stats-note">Танилцуулгын загварт ашигласан жишээ үзүүлэлтүүд.</p></div></section>
}
function Services({ onQuote }: { onQuote: (service: ServiceId) => void }) {
  return <section id="services" className="services section-pad" aria-labelledby="services-title"><div className="wrap">
    <Reveal className="section-heading"><div><Label number="01">БИДНИЙ ҮЙЛЧИЛГЭЭ</Label><h2 id="services-title">Нэг төлөвлөгөө.<br /><span>Цогц гүйцэтгэл.</span></h2></div><p>Төслийн эхний санаанаас эцсийн гүйцэтгэл хүртэл. Танд хэрэгтэй ажлыг нэг дороос.</p></Reveal>
    <div className="service-list">{services.map((service, index) => <Reveal key={service.id}><article className="service-row"><span className="service-number">0{index + 1}</span><div className="service-name"><Icon name={service.icon} /><h3>{service.title}</h3></div><div className="service-description"><p>{service.description}</p><span>{service.detail}</span></div><QuoteLink className="service-link" onClick={() => onQuote(service.id)}><span className="sr-only">{service.title} — </span>Ярилцах</QuoteLink></article></Reveal>)}</div>
  </div></section>
}
function Projects({ onOpen }: { onOpen: (project: Project) => void }) {
  const [filter, setFilter] = useState('all')
  const visible = projects.filter(project => filter === 'all' || project.group === filter)
  return <section id="projects" className="projects section-pad" aria-labelledby="projects-title"><div className="wrap">
    <Reveal className="section-heading"><div><Label number="02">ОНЦЛОХ ТӨСЛҮҮД</Label><h2 id="projects-title">Орон зай бүр<br /><span>өөрийн шийдэлтэй.</span></h2></div><p>Амьдрах, ажиллах, үйлчлүүлэх орон зай.<br />Бидний ажлын чиглэлийг харуулах загвар төслүүд.</p></Reveal>
    <div className="project-toolbar"><div className="project-filters" role="group" aria-label="Төслийн ангилал">{[{ id: 'all', name: 'Бүгд' }, { id: 'interior', name: 'Интерьер' }, { id: 'construction', name: 'Барилга' }].map(item => <button type="button" key={item.id} aria-pressed={filter === item.id} onClick={() => setFilter(item.id)}>{item.name}</button>)}</div><span className="project-count" aria-live="polite">{String(visible.length).padStart(2, '0')} төсөл</span></div>
    <div className="project-grid grid grid-cols-1 md:grid-cols-2">{visible.map(project => <Reveal key={project.id}><button type="button" className="project-card" onClick={() => onOpen(project)} aria-label={project.name + ' — төслийн дэлгэрэнгүй'}><div className="project-image"><img src={project.image} alt={project.alt} width="1100" height="733" loading="lazy" /><span className="project-index">{project.id} /</span><span className="project-open"><Icon name="arrow" /></span></div><div className="project-meta"><div><span className="project-category">{project.category}</span><h3>{project.name}</h3><p>{project.location}</p></div><span className="project-year">{project.year}</span></div></button></Reveal>)}</div>
    <p className="project-note">Төслийн мэдээлэл нь жишээ бөгөөд гэрэл зургуудыг загварын зориулалтаар ашиглав.</p>
  </div></section>
}
function About() {
  return <section id="about" className="about" aria-labelledby="about-title"><div className="about-photo"><img src="/images/planning.jpg" alt="Архитектор барилгын зураг төсөл дээр хэмжилт, тэмдэглэгээ хийж буй нь" width="1000" height="563" loading="lazy" /><div className="drawing-caption"><span className="crosshair" aria-hidden="true">+</span><span>ЗУРАГ ТӨСӨЛ / ГҮЙЦЭТГЭЛ</span><span>NB—01</span></div></div><div className="about-panel"><Reveal><Label number="03">NOMAD BUILD-ИЙН ТУХАЙ</Label><h2 id="about-title">Төлөвлөлтөөс<br /><span>гүйцэтгэл хүртэл.</span></h2><p className="about-lead">Сайхан харагдахаас гадна хэрэглэхэд тухтай орон зайг бид чухалчилдаг.</p><p>Төсөл бүрийг таны хэрэгцээг ойлгохоос эхлүүлнэ. Талбайн онцлог, төсөв, хугацаанд нийцсэн шийдлийг хамтдаа сонгож, ажлаа тодорхой үе шаттай төлөвлөнө.</p><p>Материалын сонголтоос эцсийн угсралт хүртэл жижиг зүйлсийг ч орхигдуулахгүй. Ажлын явцыг нээлттэй ярилцаж, өөрчлөлт бүрийг тантай тохиролцоно.</p><a href="#process" className="inline-link">Бид хэрхэн ажилладаг вэ?<Icon name="arrow" /></a><div className="about-signoff"><span>NOMAD Build</span><span>САНАА. ТӨЛӨВЛӨЛТ. ГҮЙЦЭТГЭЛ.</span></div></Reveal></div></section>
}
function Process() {
  return <section id="process" className="process section-pad" aria-labelledby="process-title"><div className="wrap"><Reveal className="section-heading"><div><Label number="04">АЖЛЫН ДАРААЛАЛ</Label><h2 id="process-title">Алхам бүр<br /><span>ойлгомжтой.</span></h2></div><p>Юу хийх, хэдийд дуусах, ямар үр дүн хүлээхийг эхнээс нь хамт тодорхойлно.</p></Reveal><div className="process-grid grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">{process.map((step, i) => <Reveal className="process-step" key={step.title}><span className="step-number">0{i + 1}</span><div className="step-line"><span /></div><h3>{step.title}</h3><p>{step.text}</p></Reveal>)}</div></div></section>
}
function Principles() {
  return <section className="principles section-pad" aria-labelledby="principles-title"><div className="wrap principles-grid"><Reveal><Label number="05">БИДНИЙ БАРИМТЛАХ ЗАРЧИМ</Label><h2 id="principles-title">Итгэл даах<br /><span>ажлын арга.</span></h2><p className="principles-intro">Харилцаа тодорхой байвал ажил урагшилдаг. Бид дараах зарчмыг өдөр тутмын ажилдаа баримтална.</p><div className="blueprint" aria-hidden="true"><svg viewBox="0 0 500 210" fill="none"><path d="M50 30h400v150H50V30ZM200 30v75h250M200 180v-45M50 110h80M150 110h50M300 105v75M50 24V8m400 16V8M50 14h400M465 30h22m-22 150h22M477 30v150" stroke="currentColor" strokeWidth="1.5" /><path d="M200 135a30 30 0 0 1 30-30m-30 30 30-30M130 110a20 20 0 0 1 20-20m0 20V90" stroke="currentColor" strokeWidth="1" /><path d="M76 51h91v34H76zM325 122h92v35h-92z" stroke="currentColor" opacity=".5" /><circle cx="380" cy="67" r="19" stroke="currentColor" /><path d="M15 200h45m-22-22v44" stroke="currentColor" /></svg><span>NB / АЖЛЫН ЗАРЧИМ</span></div></Reveal><div className="principle-list">{benefits.map((benefit, i) => <Reveal key={benefit.title} className="principle"><span>0{i + 1}</span><div><h3>{benefit.title}</h3><p>{benefit.text}</p></div><Icon name="check" /></Reveal>)}</div></div></section>
}
function Testimonials() {
  return <section className="testimonials section-pad" aria-labelledby="reviews-title"><div className="wrap"><Reveal className="section-heading"><div><Label number="06">ХАРИЛЦАГЧДЫН СЭТГЭГДЭЛ</Label><h2 id="reviews-title">Хамтын ажлын<br /><span>тухай.</span></h2></div><p>Хүлээлт, харилцаа, гүйцэтгэл.<br />Харилцагчийн өнцгөөс.</p></Reveal><div className="review-grid grid grid-cols-1 md:grid-cols-3">{reviews.map(review => <Reveal key={review.name}><figure className="review"><span className="quote-mark" aria-hidden="true">“</span><blockquote>{review.text}</blockquote><figcaption><strong>{review.name}</strong><span>{review.role}</span></figcaption></figure></Reveal>)}</div><p className="project-note">Сэтгэгдлүүдийг танилцуулгын загварт зориулан зохиов.</p></div></section>
}
function CallToAction() {
  return <section className="cta" aria-labelledby="cta-title"><div className="wrap cta-inner"><Reveal><Label>ДАРААГИЙН АЛХАМ</Label><h2 id="cta-title">Дараагийн төслөө<br />хамт эхлүүлье.</h2><p>Танд санаа бий. Түүнийг хэрэгжүүлэх төлөвлөгөөг хамт гаргая.</p></Reveal><QuoteLink className="button-dark" /><span className="cta-axis" aria-hidden="true">↗</span></div></section>
}
function Contact({ selectedService, onServiceChange }: { selectedService: ServiceId | ''; onServiceChange: (service: ServiceId | '') => void }) {
  return <section id="contact" className="contact section-pad" aria-labelledby="contact-title"><div className="wrap contact-grid"><Reveal className="contact-info"><Label number="07">ХОЛБОО БАРИХ</Label><h2 id="contact-title">Таны төсөл<br /><span>эндээс эхэлнэ.</span></h2><p className="contact-lead">Шинэ орон зай төлөвлөж байна уу?<br />Хийлгэх ажлынхаа талаар бидэнтэй ярилцаарай.</p><div className="contact-item"><Icon name="phone" /><div><h3>Утас</h3><a className="contact-phone" href={contact.phoneHref}>{contact.phone}</a></div></div><div className="contact-item"><Icon name="mail" /><div><h3>И-мэйл</h3><a href={'mailto:' + contact.email}>{contact.email}</a></div></div><div className="contact-item"><Icon name="pin" /><div><h3>Оффисын хаяг</h3><address>{contact.address}<br />{contact.addressLine}</address></div></div><div className="office-hours"><span className="status-dot" /><p>Даваа – Баасан <strong>09:00 – 18:00</strong></p></div><p className="demo-note">Хаяг, утас, ажиллах цаг нь жишээ мэдээлэл.</p></Reveal><Reveal><ContactForm selectedService={selectedService} onServiceChange={onServiceChange} /></Reveal></div></section>
}
function Footer() {
  return <footer className="footer"><div className="wrap"><div className="footer-main"><div className="footer-brand"><Logo /><p>Бодит хэрэгцээ.<br />Бодит шийдэл.</p></div><nav aria-label="Хуудасны доод цэс">{navigation.slice(1).map(item => <a href={item.href} key={item.href}>{item.label}</a>)}</nav><div className="footer-contact"><a href={contact.phoneHref}>{contact.phone}</a><a href={'mailto:' + contact.email}>{contact.email}</a><span>Улаанбаатар, Монгол</span></div><div className="footer-social"><a href={contact.facebook} target="_blank" rel="noopener noreferrer" aria-label="Facebook — жишээ холбоос, шинэ цонхонд">Facebook<Icon name="arrow" /></a><a href={contact.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram — жишээ холбоос, шинэ цонхонд">Instagram<Icon name="arrow" /></a></div></div><div className="footer-bottom"><p>© {new Date().getFullYear()} NOMAD Build</p><p>Портфолио загвар · Бодит компани биш.</p><a href="#home">Эхлэл рүү ↑</a></div></div></footer>
}
export default function App() {
  const [project, setProject] = useState<Project | null>(null)
  const [selectedService, setSelectedService] = useState<ServiceId | ''>('')
  return <><a className="skip-link" href="#main">Үндсэн агуулга руу очих</a><Navbar /><main id="main"><Hero /><Stats /><Services onQuote={setSelectedService} /><Projects onOpen={setProject} /><About /><Process /><Principles /><Testimonials /><CallToAction /><Contact selectedService={selectedService} onServiceChange={setSelectedService} /></main><Footer />{project && <ProjectDialog project={project} onClose={() => setProject(null)} onQuote={setSelectedService} />}</>
}
